export const RouteNames = {
  login: "/auth/login",
  index: "/",
  account: "/account",
  areas: "/areas",
  areasAdd: "/areas/add",
  areasEdit: "/areas/[id]/edit",
  managers: "/managers",
  managersView: "/managers/[id]",
  managersEdit: "/managers/[id]/edit",
  managersAdd: "/managers/add",
  volunteers: "/volunteers",
  volunteersView: "/volunteers/[id]",
  volunteersEdit: "/volunteers/[id]/edit",
  volunteersAdd: "/volunteers/add",
  reports: "/reports",
  reportsEdit: "/reports/[id]",
  postCategories: "/post-categories",
  posts: "/posts",
  postAdd: "/posts/add",
  postEdit: "/posts/[id]/edit",
  users: "/users",
  userEdit: "/users/[id]/edit",
};

export default RouteNames;
